# GoReleaser configuration for Howto
# AI-powered command-line assistant
# Keywords: AI, CLI, terminal, shell, commands, assistant
# Documentation: https://goreleaser.com

project_name: howto

version: 2

# Metadata for the project
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"

before:
  hooks:
    - go mod tidy
    - go mod verify

builds:
  - id: howto
    binary: howto
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "Performance improvements"
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

brews:
  - repository:
      owner: techquestsdev
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TOKEN }}"
    name: howto
    homepage: https://github.com/techquestsdev/howto
    description: "AI-powered command-line assistant for shell commands"
    license: MIT
    skip_upload: auto
    # Keywords for Homebrew discoverability
    caveats: |
      Howto is an AI-powered command-line tool that suggests shell commands.
      Set your API key to get started:
        export OPENAI_API_KEY=your-key    # For OpenAI
        export ANTHROPIC_API_KEY=your-key # For Anthropic/Claude
        export GEMINI_API_KEY=your-key    # For Google Gemini
        export GITHUB_TOKEN=your-token    # For GitHub Copilot
      
      Usage: howto "your natural language query"

release:
  github:
    owner: techquestsdev
    name: howto
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Howto {{ .Tag }} ({{ .Date }})

    AI-powered command-line assistant for shell commands.
    Supports OpenAI, Anthropic, Google Gemini, DeepSeek, and GitHub Copilot.
  footer: |
    **Full Changelog**: https://github.com/techquestsdev/howto/compare/{{ .PreviousTag }}...{{ .Tag }}
